notifications:
  email: false

language: php

php:
  - 5.4

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  
script:
  - phpcs -np --encoding=utf-8 --extensions=php --standard=PEAR --report=full tools
  - phpcs -np --encoding=utf-8 --extensions=php --standard=PEAR --report=full vendor/csphere