notifications:
  email: false

language: php

php:
  - 5.4

before_script:
  - pear channel-discover pear.phpmd.org
  - pear config-set auto_discover 1
  - pear install phpmd/PHP_PMD
  - pear install pear.phpunit.de/phpcpd
  - pear install PHP_CodeSniffer
  - phpenv rehash
  
script:
  - phpcpd csphere
  - phpcs -n --encoding=utf-8 --extensions=php --standard=PEAR --report=full csphere
  - phpmd csphere text codesize,design,naming,unusedcode